import type { City, Army } from "./types";

export const initialCities: City[] = [
  {
    id: "samarkand",
    name: "Samarqand",
    position: [0, 0, 0],
    defenseLevel: 5,
    conquered: true,
    faction: "timurid",
    description: "Temur imperiyasining poytaxti",
    year: "1370",
  },
  {
    id: "baghdad",
    name: "Bag'dod",
    position: [-25, 0, 15],
    defenseLevel: 8,
    conquered: false,
    faction: "enemy",
    description: "Bag'dod muhosarasi",
    year: "1393",
  },
  {
    id: "delhi",
    name: "Dehli",
    position: [20, 0, 25],
    defenseLevel: 7,
    conquered: false,
    faction: "enemy",
    description: "Hindiston sultonligi poytaxti",
    year: "1398",
  },
  {
    id: "ankara",
    name: "Anqara",
    position: [-35, 0, -10],
    defenseLevel: 9,
    conquered: false,
    faction: "enemy",
    description: "Usmonli imperiyasi markazi",
    year: "1402",
  },
  {
    id: "terek",
    name: "Terek",
    position: [-15, 0, -25],
    defenseLevel: 6,
    conquered: false,
    faction: "enemy",
    description: "Oltin O'rda hududlari",
    year: "1395",
  },
  {
    id: "kondurcha",
    name: "Kondurcha",
    position: [-5, 0, -20],
    defenseLevel: 7,
    conquered: false,
    faction: "enemy",
    description: "To'xtamish xon qo'shinlari",
    year: "1391",
  },
  {
    id: "herat",
    name: "Hirot",
    position: [12, 0, 8],
    defenseLevel: 4,
    conquered: false,
    faction: "neutral",
    description: "Xuroson viloyati markazi",
    year: "1381",
  },
  {
    id: "tabriz",
    name: "Tabriz",
    position: [-20, 0, -5],
    defenseLevel: 6,
    conquered: false,
    faction: "enemy",
    description: "Jaloyiriylar poytaxti",
    year: "1386",
  },
];

export const initialArmies: Army[] = [
  {
    id: "temur-main",
    faction: "timurid",
    position: [2, 0, 2],
    targetPosition: null,
    troops: 50000,
    type: "mixed",
    selected: false,
    health: 100,
    maxHealth: 100,
    speed: 0.08,
    inBattle: false,
  },
  {
    id: "temur-cavalry",
    faction: "timurid",
    position: [-3, 0, -2],
    targetPosition: null,
    troops: 15000,
    type: "cavalry",
    selected: false,
    health: 100,
    maxHealth: 100,
    speed: 0.12,
    inBattle: false,
  },
  {
    id: "enemy-baghdad",
    faction: "enemy",
    position: [-23, 0, 13],
    targetPosition: null,
    troops: 30000,
    type: "mixed",
    selected: false,
    health: 100,
    maxHealth: 100,
    speed: 0.04,
    inBattle: false,
    patrolRoute: [[-23, 0, 13], [-27, 0, 17], [-23, 0, 17], [-27, 0, 13]],
    patrolIndex: 0,
  },
  {
    id: "enemy-delhi",
    faction: "enemy",
    position: [18, 0, 23],
    targetPosition: null,
    troops: 40000,
    type: "infantry",
    selected: false,
    health: 100,
    maxHealth: 100,
    speed: 0.03,
    inBattle: false,
    patrolRoute: [[18, 0, 23], [22, 0, 27], [18, 0, 27]],
    patrolIndex: 0,
  },
  {
    id: "enemy-ankara",
    faction: "enemy",
    position: [-33, 0, -8],
    targetPosition: null,
    troops: 35000,
    type: "cavalry",
    selected: false,
    health: 100,
    maxHealth: 100,
    speed: 0.05,
    inBattle: false,
    patrolRoute: [[-33, 0, -8], [-37, 0, -12], [-33, 0, -12]],
    patrolIndex: 0,
  },
];

export const quizQuestions: Record<string, {
  question: string;
  options: { key: string; label: string }[];
  correctKey: string;
  battleName: string;
}> = {
  baghdad: {
    question: "Temur Bag'dodni qachon zabt etgan?",
    options: [
      { key: "A", label: "1393-yil" },
      { key: "B", label: "1398-yil" },
      { key: "C", label: "1402-yil" },
      { key: "D", label: "1387-yil" },
    ],
    correctKey: "A",
    battleName: "Bag'dod muhosarasi",
  },
  delhi: {
    question: "Amir Temur Hindistonga qaysi yilda yurish qilgan?",
    options: [
      { key: "A", label: "1395-yil" },
      { key: "B", label: "1398-yil" },
      { key: "C", label: "1402-yil" },
      { key: "D", label: "1388-yil" },
    ],
    correctKey: "B",
    battleName: "Dehli jangi",
  },
  ankara: {
    question: "Anqara jangida Temur kimni mag'lub qilgan?",
    options: [
      { key: "A", label: "To'xtamish xon" },
      { key: "B", label: "Boyazid I" },
      { key: "C", label: "Sulton Mahmud" },
      { key: "D", label: "Ahmad Jaloyir" },
    ],
    correctKey: "B",
    battleName: "Anqara jangi",
  },
  terek: {
    question: "Terek daryosi jangi kimga qarshi bo'lgan?",
    options: [
      { key: "A", label: "Boyazid I" },
      { key: "B", label: "Ahmad Jaloyir" },
      { key: "C", label: "To'xtamish xon" },
      { key: "D", label: "Nasir ud-Din Mahmud" },
    ],
    correctKey: "C",
    battleName: "Terek daryosi jangi",
  },
  kondurcha: {
    question: "Kondurcha jangi qaysi yilda bo'lgan?",
    options: [
      { key: "A", label: "1391-yil" },
      { key: "B", label: "1395-yil" },
      { key: "C", label: "1398-yil" },
      { key: "D", label: "1389-yil" },
    ],
    correctKey: "A",
    battleName: "Kondurcha jangi",
  },
  herat: {
    question: "Temur Hirotni qaysi yilda zabt etgan?",
    options: [
      { key: "A", label: "1379-yil" },
      { key: "B", label: "1381-yil" },
      { key: "C", label: "1385-yil" },
      { key: "D", label: "1377-yil" },
    ],
    correctKey: "B",
    battleName: "Hirot zabt etilishi",
  },
  tabriz: {
    question: "Tabriz qaysi davlat poytaxti bo'lgan?",
    options: [
      { key: "A", label: "Usmonli imperiyasi" },
      { key: "B", label: "Jaloyiriylar" },
      { key: "C", label: "Oltin O'rda" },
      { key: "D", label: "Chig'atoy ulusi" },
    ],
    correctKey: "B",
    battleName: "Tabriz zabt etilishi",
  },
};
