"""Add UserCertificate model

Revision ID: 003
Revises: 
Create Date: 2026-03-31 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('total_topics', sa.Integer(), nullable=False),
    sa.Column('completed_topics', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificates_certificate_number'), 'user_certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_user_certificates_user_id'), 'user_certificates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_certificates_user_id'), table_name='user_certificates')
    op.drop_index(op.f('ix_user_certificates_certificate_number'), table_name='user_certificates')
    op.drop_table('user_certificates')
    # ### end Alembic commands ###
